baseurl = "https://mossale.netlify.com/"
DefaultContentLanguage = "en"
title = "Mossale Store"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = false
pygmentsCodeFences = false
pygmentsCodefencesGuessSyntax = false

[Params]
  subtitle = "Looking for a new owner for my shoes"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  useHLJS = false
  socialShare = false
  snipcartAPIKey = "NWJkZDRiYzQtM2ZlZS00ZGEyLThhMmYtNzY0NDA0YTY1OTBlNjM3MDMzNjY2NzY2NDM2ODIy"

[Author]
  name = "Sylvia Moss"
  email = "sylviamoss.m@gmail.com"
  github = "sylviamoss"
  instagram = "mosstarda"
